Create interaction_with_students.md
IGO-enviroment/documentation_burse_project pull request #4
Opened 2024-10-30 06:57 UTC by IKnigencev

2024-11-01 13:57 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +Отдельная страница сотрудников. Роли внутри компании. Есть админ с полными правами (он будет проставляться автоматом после реги предприятия).
Как у нас будут задействованы эти сотрудники?

2024-11-01 14:08 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельный блок диалогов. Передача документов, сообщений и тд.
типо чата? real-time?

2024-11-01 14:09 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельный страница или элемент со списком с практиками, возможность фильтровать по активным, завершенным и тд.
```suggestion
***Критерии:*** Отдельный страница или элемент со списком практик, возможность фильтровать по активным, завершенным и тд.
```

2024-11-01 14:11 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельная станица со списком всех профилей студентов, возможность фильтровать по всем паратетрам и тд. Отдельная страница профиля студента.
тут две юзер стори но оставим так пусть

2024-11-01 14:16 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельная страница диалогов. Разделены по разным типам, фильтрация и поиск по ним. Отдельная форма создания нового диалога с указанием с кем, цели и тд.
обмен документами будет в диалогах? мб где то в специально отведенном месте это делать (в заявках например)?

2024-11-01 14:17 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельный страница или элемент со списком отправленных заявок, возможность фильтровать и тд.
```suggestion
***Критерии:*** Отдельная страница или элемент со списком отправленных заявок, возможность фильтровать и тд.
```

2024-11-01 15:35 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +Отдельная страница сотрудников. Роли внутри компании. Есть админ с полными правами (он будет проставляться автоматом после реги предприятия).
Пока только видится, что мы (предприятие) можем прикрепить их как кураторов практик (чтобы через них шел контакт по поводу прохождения конкретной практики).

2024-11-01 15:37 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +## - Подписаться и получать уведомлния по действиям на платформе.
```suggestion
## - Подписаться и получать уведомления по действиям на платформе.
```

2024-11-01 15:37 UTC, OvechkinDmitry requested changes
хм

2024-11-01 16:44 UTC, notanumer requested changes

2024-11-01 16:44 UTC, notanumer commented on user_story/enterprise/common_stories.md
> +Получаю апрув от автоматической проверки и могу попасть в свой ЛК.
у нас же автоматическая проверка не для апрува была, а для того, чтобы доходить для сотрудников администрации, которые уже дадут апрув?

2024-11-01 16:44 UTC, notanumer commented on user_story/enterprise/common_stories.md
> +Есть лэндинг, оттуда попадаю на отдельную страниу входа. Заполняю информацию о предприятии, указываю почту для обратной связи и получения пароля для входа. Могу ввести просто свою почту для получения
```suggestion
Есть лэндинг, оттуда попадаю на отдельную страницу входа. Заполняю информацию о предприятии, указываю почту для обратной связи и получения пароля для входа. Могу ввести свою почту для получения статуса рассмотрение заявки.
```

2024-11-01 16:44 UTC, notanumer commented on user_story/enterprise/common_stories.md
> +Можно также менять администратору прелприятия уведомления для других пользователей.
```suggestion
Можно также менять администратору предприятия уведомления для других пользователей.
```

2024-11-06 18:30 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +Получаю апрув от автоматической проверки и могу попасть в свой ЛК.
зайти можем в систему, но аппрув да нужен будет иначе как организация не отобразимся ни для кого в системе

2024-11-06 18:36 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +Отдельная страница сотрудников. Роли внутри компании. Есть админ с полными правами (он будет проставляться автоматом после реги предприятия).
Для mvp просто закрепление пользователя за предприятие без разграничений по ролям
(делаем хоть что просто от какого то пользователя которому дан доступ)

2024-11-07 16:03 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +Отдельная страница с размещенным от университетов предложениями на практику для органиазций, с указанием направлений, темы, количеством учестников и тд
в самой платформе по идее должен быть список направлений, зачем университетам  заниматься предложением практик и размещать что то (мб что т не понимаю подробнее надо)

2024-11-07 16:05 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Отдельная страница или элемент со списком отправленных заявок, возможность фильтровать и тд.
обсуждали что практика может быть создана без ведома института, но тогда их нужно будет каким то образом валидировать мб?

2024-11-07 16:08 UTC, OvechkinDmitry commented on user_story/enterprise/common_stories.md
> +***Критерии:*** Обязательные поля контактов в профиле студента, также возможность перейти и создать диалог с любым студентом.
диалог в виде чего?

2024-12-08 12:33 UTC, merged